'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace DemoFinkok
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Application", [Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class StampSOAP
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private sign_stampOperationCompleted As System.Threading.SendOrPostCallback
        
        Private stampedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private stampOperationCompleted As System.Threading.SendOrPostCallback
        
        Private query_pendingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private get_pdfOperationCompleted As System.Threading.SendOrPostCallback
        
        Private quick_stampOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MobileNOMv2.My.MySettings.Default.MobileNOMv2_DemoFinkok_StampSOAP
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event sign_stampCompleted As sign_stampCompletedEventHandler
        
        '''<remarks/>
        Public Event stampedCompleted As stampedCompletedEventHandler
        
        '''<remarks/>
        Public Event stampCompleted As stampCompletedEventHandler
        
        '''<remarks/>
        Public Event query_pendingCompleted As query_pendingCompletedEventHandler
        
        '''<remarks/>
        Public Event get_pdfCompleted As get_pdfCompletedEventHandler
        
        '''<remarks/>
        Public Event quick_stampCompleted As quick_stampCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("sign_stamp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function sign_stamp(<System.Xml.Serialization.XmlElementAttribute("sign_stamp", [Namespace]:="http://facturacion.finkok.com/stamp")> ByVal sign_stamp1 As sign_stamp) As <System.Xml.Serialization.XmlElementAttribute("sign_stampResponse", [Namespace]:="http://facturacion.finkok.com/stamp")> sign_stampResponse
            Dim results() As Object = Me.Invoke("sign_stamp", New Object() {sign_stamp1})
            Return CType(results(0),sign_stampResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub sign_stampAsync(ByVal sign_stamp1 As sign_stamp)
            Me.sign_stampAsync(sign_stamp1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub sign_stampAsync(ByVal sign_stamp1 As sign_stamp, ByVal userState As Object)
            If (Me.sign_stampOperationCompleted Is Nothing) Then
                Me.sign_stampOperationCompleted = AddressOf Me.Onsign_stampOperationCompleted
            End If
            Me.InvokeAsync("sign_stamp", New Object() {sign_stamp1}, Me.sign_stampOperationCompleted, userState)
        End Sub
        
        Private Sub Onsign_stampOperationCompleted(ByVal arg As Object)
            If (Not (Me.sign_stampCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent sign_stampCompleted(Me, New sign_stampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("stamped", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function stamped(<System.Xml.Serialization.XmlElementAttribute("stamped", [Namespace]:="http://facturacion.finkok.com/stamp")> ByVal stamped1 As stamped) As <System.Xml.Serialization.XmlElementAttribute("stampedResponse", [Namespace]:="http://facturacion.finkok.com/stamp")> stampedResponse
            Dim results() As Object = Me.Invoke("stamped", New Object() {stamped1})
            Return CType(results(0),stampedResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub stampedAsync(ByVal stamped1 As stamped)
            Me.stampedAsync(stamped1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub stampedAsync(ByVal stamped1 As stamped, ByVal userState As Object)
            If (Me.stampedOperationCompleted Is Nothing) Then
                Me.stampedOperationCompleted = AddressOf Me.OnstampedOperationCompleted
            End If
            Me.InvokeAsync("stamped", New Object() {stamped1}, Me.stampedOperationCompleted, userState)
        End Sub
        
        Private Sub OnstampedOperationCompleted(ByVal arg As Object)
            If (Not (Me.stampedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent stampedCompleted(Me, New stampedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("stamp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function stamp(<System.Xml.Serialization.XmlElementAttribute("stamp", [Namespace]:="http://facturacion.finkok.com/stamp")> ByVal stamp1 As stamp) As <System.Xml.Serialization.XmlElementAttribute("stampResponse", [Namespace]:="http://facturacion.finkok.com/stamp")> stampResponse
            Dim results() As Object = Me.Invoke("stamp", New Object() {stamp1})
            Return CType(results(0),stampResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub stampAsync(ByVal stamp1 As stamp)
            Me.stampAsync(stamp1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub stampAsync(ByVal stamp1 As stamp, ByVal userState As Object)
            If (Me.stampOperationCompleted Is Nothing) Then
                Me.stampOperationCompleted = AddressOf Me.OnstampOperationCompleted
            End If
            Me.InvokeAsync("stamp", New Object() {stamp1}, Me.stampOperationCompleted, userState)
        End Sub
        
        Private Sub OnstampOperationCompleted(ByVal arg As Object)
            If (Not (Me.stampCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent stampCompleted(Me, New stampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("query_pending", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function query_pending(<System.Xml.Serialization.XmlElementAttribute("query_pending", [Namespace]:="http://facturacion.finkok.com/stamp")> ByVal query_pending1 As query_pending) As <System.Xml.Serialization.XmlElementAttribute("query_pendingResponse", [Namespace]:="http://facturacion.finkok.com/stamp")> query_pendingResponse
            Dim results() As Object = Me.Invoke("query_pending", New Object() {query_pending1})
            Return CType(results(0),query_pendingResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub query_pendingAsync(ByVal query_pending1 As query_pending)
            Me.query_pendingAsync(query_pending1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub query_pendingAsync(ByVal query_pending1 As query_pending, ByVal userState As Object)
            If (Me.query_pendingOperationCompleted Is Nothing) Then
                Me.query_pendingOperationCompleted = AddressOf Me.Onquery_pendingOperationCompleted
            End If
            Me.InvokeAsync("query_pending", New Object() {query_pending1}, Me.query_pendingOperationCompleted, userState)
        End Sub
        
        Private Sub Onquery_pendingOperationCompleted(ByVal arg As Object)
            If (Not (Me.query_pendingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent query_pendingCompleted(Me, New query_pendingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_pdf", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function get_pdf(<System.Xml.Serialization.XmlElementAttribute("get_pdf", [Namespace]:="http://facturacion.finkok.com/stamp")> ByVal get_pdf1 As get_pdf) As <System.Xml.Serialization.XmlElementAttribute("get_pdfResponse", [Namespace]:="http://facturacion.finkok.com/stamp")> get_pdfResponse
            Dim results() As Object = Me.Invoke("get_pdf", New Object() {get_pdf1})
            Return CType(results(0),get_pdfResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub get_pdfAsync(ByVal get_pdf1 As get_pdf)
            Me.get_pdfAsync(get_pdf1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub get_pdfAsync(ByVal get_pdf1 As get_pdf, ByVal userState As Object)
            If (Me.get_pdfOperationCompleted Is Nothing) Then
                Me.get_pdfOperationCompleted = AddressOf Me.Onget_pdfOperationCompleted
            End If
            Me.InvokeAsync("get_pdf", New Object() {get_pdf1}, Me.get_pdfOperationCompleted, userState)
        End Sub
        
        Private Sub Onget_pdfOperationCompleted(ByVal arg As Object)
            If (Not (Me.get_pdfCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent get_pdfCompleted(Me, New get_pdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("quick_stamp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function quick_stamp(<System.Xml.Serialization.XmlElementAttribute("quick_stamp", [Namespace]:="http://facturacion.finkok.com/stamp")> ByVal quick_stamp1 As quick_stamp) As <System.Xml.Serialization.XmlElementAttribute("quick_stampResponse", [Namespace]:="http://facturacion.finkok.com/stamp")> quick_stampResponse
            Dim results() As Object = Me.Invoke("quick_stamp", New Object() {quick_stamp1})
            Return CType(results(0),quick_stampResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub quick_stampAsync(ByVal quick_stamp1 As quick_stamp)
            Me.quick_stampAsync(quick_stamp1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub quick_stampAsync(ByVal quick_stamp1 As quick_stamp, ByVal userState As Object)
            If (Me.quick_stampOperationCompleted Is Nothing) Then
                Me.quick_stampOperationCompleted = AddressOf Me.Onquick_stampOperationCompleted
            End If
            Me.InvokeAsync("quick_stamp", New Object() {quick_stamp1}, Me.quick_stampOperationCompleted, userState)
        End Sub
        
        Private Sub Onquick_stampOperationCompleted(ByVal arg As Object)
            If (Not (Me.quick_stampCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent quick_stampCompleted(Me, New quick_stampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class sign_stamp
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class quick_stampResponse
        
        Private quick_stampResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property quick_stampResult() As AcuseRecepcionCFDI
            Get
                Return Me.quick_stampResultField
            End Get
            Set
                Me.quick_stampResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class AcuseRecepcionCFDI
        
        Private xmlField As String
        
        Private uUIDField As String
        
        Private faultstringField As String
        
        Private fechaField As String
        
        Private codEstatusField As String
        
        Private faultcodeField As String
        
        Private satSealField As String
        
        Private incidenciasField() As Incidencia
        
        Private noCertificadoSATField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property xml() As String
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property faultstring() As String
            Get
                Return Me.faultstringField
            End Get
            Set
                Me.faultstringField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodEstatus() As String
            Get
                Return Me.codEstatusField
            End Get
            Set
                Me.codEstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property faultcode() As String
            Get
                Return Me.faultcodeField
            End Get
            Set
                Me.faultcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SatSeal() As String
            Get
                Return Me.satSealField
            End Get
            Set
                Me.satSealField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Incidencias() As Incidencia()
            Get
                Return Me.incidenciasField
            End Get
            Set
                Me.incidenciasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NoCertificadoSAT() As String
            Get
                Return Me.noCertificadoSATField
            End Get
            Set
                Me.noCertificadoSATField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class Incidencia
        
        Private idIncidenciaField As String
        
        Private rfcEmisorField As String
        
        Private uuidField As String
        
        Private codigoErrorField As String
        
        Private workProcessIdField As String
        
        Private mensajeIncidenciaField As String
        
        Private extraInfoField As String
        
        Private noCertificadoPacField As String
        
        Private fechaRegistroField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdIncidencia() As String
            Get
                Return Me.idIncidenciaField
            End Get
            Set
                Me.idIncidenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoError() As String
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property WorkProcessId() As String
            Get
                Return Me.workProcessIdField
            End Get
            Set
                Me.workProcessIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MensajeIncidencia() As String
            Get
                Return Me.mensajeIncidenciaField
            End Get
            Set
                Me.mensajeIncidenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ExtraInfo() As String
            Get
                Return Me.extraInfoField
            End Get
            Set
                Me.extraInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NoCertificadoPac() As String
            Get
                Return Me.noCertificadoPacField
            End Get
            Set
                Me.noCertificadoPacField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FechaRegistro() As String
            Get
                Return Me.fechaRegistroField
            End Get
            Set
                Me.fechaRegistroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class quick_stamp
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class PDFResult
        
        Private pdfField() As Byte
        
        Private errorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property pdf() As Byte()
            Get
                Return Me.pdfField
            End Get
            Set
                Me.pdfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class get_pdfResponse
        
        Private get_pdfResultField As PDFResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property get_pdfResult() As PDFResult
            Get
                Return Me.get_pdfResultField
            End Get
            Set
                Me.get_pdfResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class get_pdf
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private uuidField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class QueryPendingResult
        
        Private statusField As String
        
        Private xmlField As String
        
        Private uuidField As String
        
        Private uuid_statusField As String
        
        Private next_attemptField As String
        
        Private attemptsField As String
        
        Private errorField As String
        
        Private dateField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property xml() As String
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property uuid_status() As String
            Get
                Return Me.uuid_statusField
            End Get
            Set
                Me.uuid_statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property next_attempt() As String
            Get
                Return Me.next_attemptField
            End Get
            Set
                Me.next_attemptField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property attempts() As String
            Get
                Return Me.attemptsField
            End Get
            Set
                Me.attemptsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class query_pendingResponse
        
        Private query_pendingResultField As QueryPendingResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property query_pendingResult() As QueryPendingResult
            Get
                Return Me.query_pendingResultField
            End Get
            Set
                Me.query_pendingResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class query_pending
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private uuidField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stampResponse
        
        Private stampResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property stampResult() As AcuseRecepcionCFDI
            Get
                Return Me.stampResultField
            End Get
            Set
                Me.stampResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stamp
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stampedResponse
        
        Private stampedResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property stampedResult() As AcuseRecepcionCFDI
            Get
                Return Me.stampedResultField
            End Get
            Set
                Me.stampedResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stamped
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class sign_stampResponse
        
        Private sign_stampResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property sign_stampResult() As AcuseRecepcionCFDI
            Get
                Return Me.sign_stampResultField
            End Get
            Set
                Me.sign_stampResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub sign_stampCompletedEventHandler(ByVal sender As Object, ByVal e As sign_stampCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class sign_stampCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As sign_stampResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),sign_stampResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub stampedCompletedEventHandler(ByVal sender As Object, ByVal e As stampedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class stampedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As stampedResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),stampedResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub stampCompletedEventHandler(ByVal sender As Object, ByVal e As stampCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class stampCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As stampResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),stampResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub query_pendingCompletedEventHandler(ByVal sender As Object, ByVal e As query_pendingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class query_pendingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As query_pendingResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),query_pendingResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub get_pdfCompletedEventHandler(ByVal sender As Object, ByVal e As get_pdfCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class get_pdfCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As get_pdfResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),get_pdfResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub quick_stampCompletedEventHandler(ByVal sender As Object, ByVal e As quick_stampCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class quick_stampCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As quick_stampResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),quick_stampResponse)
            End Get
        End Property
    End Class
End Namespace
